#!/usr/bin/env python3
"""Generates DA_20260818_H16_replan8_MF_UNet.md from source data.

Sources:
  gen_DA_20260818_rows.json - parsed from the 234 eval_*.log files of Slurm job 24650
        (temp/1808/H16_*_dp0.5/H16_K{1,2,5}_*MeanFlowODE[_msgr8]/6/results/halfspace_*/)
  H8 CSV - temp/1708/batch_avoiding_combined_20260817_092728/
           candidates_multidimensional_aggregated.csv

Usage:  python3 gen_DA_20260818.py > DA_20260818_H16_replan8_MF_UNet.md
Every number in the output is computed here; none is typed by hand.
"""
import sys, os, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_DA_20260818_facts import *

O = []
w = lambda s='': O.append(s)

DV, HV = 'dpcc-c-tightened', 'hardflow_new-c-tightened'
PAIRS = [(K, v) for K in (1, 2, 5) for v in (DV, HV)]
NAME = {DV: '`dpcc-c-tightened`', HV: '`hardflow_new-c-t`'}
CFG = [('H8 / r1', G8, 1, 'n=60'), ('H16 / r1', G16r1, 1, 'n=6'), ('H16 / r8', G16r8, 8, 'n=6')]
D = {(c, K): decomp(c, K) for c in ('H8', 'H16') for K in (1, 2, 5)}

def bm(cfg, K):
    """batch-matched costs: (DPCC as-run B=4, HF as-run B=1, DPCC at B=1, HF at B=4)"""
    u, s, i, dp, hf = D[(cfg, K)]
    return dp, hf, K * u + NA[K] * s, (K + NA[K]) * u + NA[K] * 4 * i

# ───────────────────────── header ─────────────────────────
w('# DA — H16 + replan-8 ("H8+8") vs H8 per-step, MeanFlow/UNet, avoiding-d3il')
w()
w('**Date:** 2026-08-18 · **Job:** 24650 (`eval_meanflow_hardflow`), i6-gpu-1, git `5bc5db4` (tree dirty)  ')
w('**Run:** `MF_HORIZON=16  MF_BACKBONE=unet  MF_REPLAN_STEPS=8  HFFM_BATCH=1  MF_FLOW_STEPS="1 2 5"`  ')
w('**Log:** `temp/1808/16_50_20_eval_meanflow_hardflow_24650.log` — completed cleanly, JOB END 15:16:39  ')
w('**Data:** `temp/1808/H16_…_dp0.5/H16_K{1,2,5}_…MeanFlowODE_msgr8/` (r8) and `…MeanFlowODE/` (r1)  ')
w('**H8 reference:** `temp/1708/batch_avoiding_combined_20260817_092728/candidates_multidimensional_aggregated.csv`, `H8_K{1,2,5}_…A0.5_B1_…_msg20trials`')
w()
w('**Three configurations compared throughout:**')
w()
w('| tag | horizon | replan every | episodes per cell |')
w('|---|---|---|---|')
w('| `H8 / r1` | 8 | 1 step | 60 (20 trials × 3 scenes) |')
w('| `H16 / r1` | 16 | 1 step | 6 (2 trials × 3 scenes) |')
w('| `H16 / r8` = **H8+8** | 16 | 8 steps | 6 (2 trials × 3 scenes) |')
w()
w('All numbers are generated by `gen_DA_20260818.py` in this folder.')
w()
w('---')
w()

# ───────────────────────── answers ─────────────────────────
w('## Answers')
w()
w('### Q1 — Does H8+8 make HardFlow win, and replan-1 make the DPCC projector win?')
w()
w('**No. The replan cadence does not decide which arm wins. The horizon and the flow-step count K do.**')
w()
w('| configuration | K=1 | K=2 | K=5 |')
w('|---|---|---|---|')
for lbl, g, n, _ in CFG:
    cells = []
    for K in (1, 2, 5):
        d = best_tight(g, 'dpcc', K); h = best_tight(g, 'hardflow', K)
        if abs(d[1] - h[1]) > 0.02:
            cells.append('**DPCC**' if d[1] > h[1] else '**HardFlow**')
        else:
            _, _, d_b1, h_b4 = bm('H8' if lbl.startswith('H8') else 'H16', K)
            cells.append('**HardFlow**' if (d_b1 / D[('H8' if lbl.startswith('H8') else 'H16', K)][4] > 1) else '**DPCC**')
    w(f'| {lbl} | ' + ' | '.join(cells) + ' |')
w()
w('The pattern runs left-to-right (K), not top-to-bottom (cadence):')
w()
w('- **The DPCC projector wins at H=8 for every K**, and at H=16 for K=1 and K=2.')
w('- **HardFlow wins only at H=16 with K=5.** It wins there under *both* cadences.')
w('- Switching r1 → r8 divides every arm\'s cost by ~8 and leaves the ranking unchanged.')
w()
w('Winner is decided on: success-and-constraints first, then cost at matched candidate count (§1.2). At H16 both families reach S&C 1.000, so cost decides — and the cost comparison is only meaningful after correcting the 4-candidate vs 1-candidate asymmetry (§1.2).')
w()
w('### Q2 — For practical use, is H16/r1 or H8+8 better than the old H8/r1?')
w()
w('**H16/r1: no. H8+8: yes, if the controller can buffer an 8-step segment; no if it cannot.**')
w()
w('| | vs old H8/r1 | verdict |')
w('|---|---|---|')
rd = [M('r1', K, v, 't_step') / M8(K, v, 't_step') for K, v in PAIRS]
w(f'| **H16 / r1** | fewer steps, but {min(rd):.1f}–{max(rd):.1f}× more expensive per env step *and* per tick | **reject** — dominated by H8/r1 on cost and by H16/r8 on cost |')
am = [M8(K, v, 't_step') / M('r8', K, v, 't_step') for K, v in PAIRS]
lat = [(M('r8', K, v, 't_step') * 8) / M8(K, v, 't_step') for K, v in PAIRS]
w(f'| **H16 / r8** (H8+8) | {min(am):.1f}–{max(am):.1f}× cheaper amortised, fewer steps, {min(lat):.1f}–{max(lat):.1f}× worse per-tick latency | **adopt if buffering is available** |')
w()
w('Cheapest configuration with S&C at or above 0.99 in each deployment regime:')
w()
w('| requirement | configuration | S&C | steps | s / env step | s / plan (worst tick) |')
w('|---|---|---|---|---|---|')
bd = best_tight(G8, 'dpcc', 1)
w(f'| bounded per-tick latency | **H8 / r1**, `{bd[0]}`, K=1 | {bd[1]:.3f} | {bd[2]:.1f} | {bd[3]:.4f} | **{bd[3]:.4f}** |')
r8b = ('dpcc-t-tightened', G16r8(2, 'dpcc-t-tightened', 'sc'), G16r8(2, 'dpcc-t-tightened', 'steps'), G16r8(2, 'dpcc-t-tightened', 't_step'))
w(f'| can buffer 8 steps | **H16 / r8**, `{r8b[0]}`, K=2 | {r8b[1]:.3f} | {r8b[2]:.1f} | **{r8b[3]:.4f}** | {r8b[3]*8:.4f} |')
w()
w(f'H8+8 at K=2 buys {bd[3]/r8b[3]:.1f}× lower total compute and {bd[2]-r8b[2]:.1f} fewer steps, and costs {r8b[3]*8/bd[3]:.1f}× higher worst-case tick latency. That is the whole trade.')
w()
w('> Both H16 rows rest on 6 episodes. The cost columns are near-deterministic; the S&C column is not (§5).')
w()
w('---')
w()
PARTS = ['\n'.join(O)]
O.clear()

# ───────────────────────── 1. Q1 detail ─────────────────────────
w('## 1. Q1 in detail — which arm wins, and why')
w()
w('### 1.1 As run')
w()
w('Best `-tightened` variant of each family (highest S&C, ties broken by fewer steps then lower cost). `S&C · steps · s per env step`.')
w()
w('| configuration | K | DPCC projector | HardFlow | as run | matched candidates (§1.2) |')
w('|---|---|---|---|---|---|')
for lbl, g, n, nn in CFG:
    cfg = 'H8' if lbl.startswith('H8') else 'H16'
    for K in (1, 2, 5):
        d = best_tight(g, 'dpcc', K); h = best_tight(g, 'hardflow', K)
        dc = cheapest_tight(g, 'dpcc', K)[3]; hc = cheapest_tight(g, 'hardflow', K)[3]
        _, _, d1, h4 = bm(cfg, K)
        hf_cheap_matched = (d1 / D[(cfg, K)][4] > 1)
        if abs(d[1] - h[1]) > 0.02:
            asrun = f'**DPCC** — S&C {d[1]:.3f} vs {h[1]:.3f}'
            fixed = '**DPCC** (S&C decides)'
        else:
            asrun = (f'S&C tied; HF {dc/hc:.1f}× cheaper' if hc < dc else f'S&C tied; DPCC {hc/dc:.1f}× cheaper')
            fixed = (f'**HardFlow** — {min(d1/D[(cfg,K)][4], D[(cfg,K)][3]/h4):.1f}–{max(d1/D[(cfg,K)][4], D[(cfg,K)][3]/h4):.1f}× cheaper'
                     if hf_cheap_matched else
                     f'**DPCC** — {min(D[(cfg,K)][4]/d1, h4/D[(cfg,K)][3]):.1f}–{max(D[(cfg,K)][4]/d1, h4/D[(cfg,K)][3]):.1f}× cheaper')
            if n == 8: fixed += ' \u2020'
        w(f'| {lbl + " (" + nn + ")" if K == 1 else ""} | {K} '
          f'| `{d[0].replace("-tightened", "-t")}` {d[1]:.3f} · {d[2]:.1f} · {d[3]:.4f} '
          f'| `hf-*-t` {h[1]:.3f} · {h[2]:.1f} · {h[3]:.4f} | {asrun} | {fixed} |')
w()
w('Cost ratios in the "as run" column use the **cheapest** tightened arm of each family; the arms named in the two data columns are the best-quality ones and are not always the cheapest. \u2020 = carried over from the H16/r1 row: the batch correction is a per-solve property and is cadence-invariant (§1.2).')
w()
w('All three HardFlow suffixes `-r/-c/-t` give identical numbers: they select among candidates, and HardFlow ran one candidate, so selection is a no-op. `hf-*-t` names them collectively.')
w()
w('### 1.2 The cost column needs a batch correction before it can be read')
w()
w('**DPCC and `diffuser` arms ran `batch_size=4`. HardFlow arms ran `B=1`.** Recorded in `run_provenance.json` (`batch_size_dpcc_arms: 4`, `hf_batch_size: 1`); the H8 CSV carries the same split.')
w()
w('The DPCC projector solves SLSQP in a sequential loop over the batch — `flow_matcher_v3_meanflow/sampling/projection.py:131`, `for i in range(batch_size): minimize(..., method=\'SLSQP\')`. Solve cost is exactly linear in B. Generation is one batched forward pass and is near-free at B=4.')
w()
w('Both families project on the same number of flow steps at threshold 0.5 — DPCC `n_proj = K - int(0.5·K)` (`models/mf_diffusion.py:283-299`), HardFlow `n_active`:')
w()
w('| K | DPCC solves / plan | HardFlow solves / plan | ratio |')
w('|---|---|---|---|')
for K in (1, 2, 5):
    w(f'| {K} | {nproj(K)} × 4 = **{nproj(K)*4}** | {NA[K]} × 1 = **{NA[K]}** | **4 : 1** |')
w()
emp = ', '.join(f'{per_plan("r1", K, HV, "nlp"):.2f}' for K in (1, 2, 5))
w(f'Confirmed against the logged counters: HardFlow NLP/plan = {emp} for K = 1, 2, 5 (§3).')
w()
w('Splitting each arm into generation and solve cost (`t = n_NFE · u + n_solves · c_solve`, with `u` taken from the projection-free `diffuser` arm at the same B=4; r1 only, because r8\'s `avg_time` is quantised to 3 decimals):')
w()
w('| configuration | K | u (s / NFE) | SLSQP per solve | IPOPT per solve |')
w('|---|---|---|---|---|')
for cfg, lbl in (('H8', 'H8 / r1'), ('H16', 'H16 / r1')):
    for K in (1, 2, 5):
        u, s, i, _, _ = D[(cfg, K)]
        w(f'| {lbl if K == 1 else ""} | {K} | {u:.5f} | {s:.5f} | {i:.5f} |')
w()
us = [D[(c, K)][0] for c in ('H8', 'H16') for K in (1, 2, 5)]
w(f'`u` lands at {min(us):.5f}–{max(us):.5f} s across all six cells regardless of K or horizon, which is the consistency check on the split.')
w()
w('Re-pricing both arms at a common candidate count:')
w()
w('| configuration | K | as run (D ÷ H) | both at B=1 | both at B=4 |')
w('|---|---|---|---|---|')
nlose = 0
for cfg, lbl in (('H8', 'H8 / r1'), ('H16', 'H16 / r1')):
    for K in (1, 2, 5):
        dp, hf, d1, h4 = bm(cfg, K)
        if d1 / hf > 1 and dp / h4 > 1: nlose += 1
        w(f'| {lbl if K == 1 else ""} | {K} | {dp/hf:.2f} | **{d1/hf:.2f}** | **{dp/h4:.2f}** |')
w()
w(f'Below 1 means the DPCC projector is cheaper. Both re-pricings agree on the sign in all six cells: **at matched candidate count HardFlow is the more expensive arm in {6-nlose} of 6 cells.** The single exception is H16 / K=5.')
w()
_, _, d1_5, h4_5 = bm('H16', 5); dp5, hf5 = D[('H16', 5)][3], D[('H16', 5)][4]
w(f'At H16 / K=5 the raw ratio reads {dp5/hf5:.1f}×; matched, it is **{min(d1_5/hf5, dp5/h4_5):.1f}–{max(d1_5/hf5, dp5/h4_5):.1f}×**. That corrected figure is the one to quote.')
w()
w('### 1.3 Why horizon flips it: the two solvers scale differently')
w()
w('| K | SLSQP per solve, H8 → H16 | IPOPT per solve, H8 → H16 |')
w('|---|---|---|')
for K in (1, 2, 5):
    _, s8, i8, _, _ = D[('H8', K)]; _, s16, i16, _, _ = D[('H16', K)]
    w(f'| {K} | {s8:.5f} → {s16:.5f} = **{s16/s8:.1f}×** | {i8:.5f} → {i16:.5f} = **{i16/i8:.2f}×** |')
w()
sr = [D[('H16', K)][1] / D[('H8', K)][1] for K in (1, 2, 5)]
ir = [D[('H16', K)][2] / D[('H8', K)][2] for K in (1, 2, 5)]
w(f'**Doubling the horizon costs SLSQP ~{sum(sr)/3:.0f}× per solve and IPOPT ~{sum(ir)/3:.2f}× per solve, at every K.** HardFlow\'s in-loop IPOPT is near-linear in the decision-variable count; DPCC\'s post-hoc dense SLSQP is superlinear (≈ H³, consistent with a dense active-set QP re-factorised each iteration over `transition_dim × H` variables).')
w()
w('SLSQP starts far cheaper per solve and loses that lead as H grows. Per-solve parity:')
w()
w('| K | SLSQP ÷ IPOPT at H8 | at H16 | extrapolated parity |')
w('|---|---|---|---|')
for K in (1, 2, 5):
    r8 = D[('H8', K)][1] / D[('H8', K)][2]; r16 = D[('H16', K)][1] / D[('H16', K)][2]
    w(f'| {K} | {r8:.2f} | {r16:.2f} | H ≈ **{8*2**(math.log(1/r8)/math.log(r16/r8)):.0f}** |')
w()
w('At K=5 the crossover has already happened by H=16. At K=1 and K=2 it has not, which is exactly the pattern in the Q1 table.')
w()
w('### 1.4 Independent confirmation')
w()
w('`DA_20260820_HF_lower_avgtime_batchsize_confound.md` measured the same quantities on a different candidate (C136, H8, K=10, 5 seeds × 20 trials):')
w()
w('| source | H | K | ms / SLSQP solve | ms / IPOPT solve | ratio |')
w('|---|---|---|---|---|---|')
_s5, _i5 = D[('H8', 5)][1] * 1000, D[('H8', 5)][2] * 1000
w(f'| job 24650, §1.2 | 8 | 5 | {_s5:.2f} | {_i5:.2f} | {_i5/_s5:.2f}× |')
w('| DA 2026-08-20 §3 | 8 | 10 | 11.50 | 20.41 | 1.78× |')
w()
w('That DA also holds the only existing measured B=4 HardFlow run (C109 / C117, H8, K=10, `both-hard`): `hardflow_new-r-tightened` at 0.4955–0.5122 s/step against `dpcc-c-tightened` at 0.3273–0.3371 — HardFlow 1.5–1.6× slower at matched batch, the sign predicted for H=8 in §1.2.')
w()
w('> ⚠️ At B=4 the `hardflow_new-c` arms collapse (161–164 steps = timeout, S&C 0.00–0.50, in C109 and C117 identically); the `prox` ranking key selects a pathological candidate. `-r` and `-t` at B=4 are fine. **Any `HFFM_BATCH=4` run must use `-r`/`-t`.** At B=1 this does not arise.')
w()
w('`resolve_hf_batch_size()` and the `HF_Batch_Parity` fix landed 2026-08-20. Job 24650 ran 2026-08-18 with `HFFM_BATCH=1` set explicitly, so the split here is the pre-fix state, deliberately configured.')
w()
w('---')
w()
PARTS.append('\n'.join(O)); O.clear()

# ───────────────────────── 2. Q2 detail ─────────────────────────
w('## 2. Q2 in detail — which configuration to run')
w()
w('Matched arms across all three configurations. `S&C · steps · s per env step`.')
w()
w('| K | arm | H8 / r1 (n=60) | H16 / r1 (n=6) | H16 / r8 (n=6) |')
w('|---|---|---|---|---|')
for K, v in PAIRS:
    w(f'| {K} | {NAME[v]} '
      f'| {M8(K,v,"sc"):.3f} · {M8(K,v,"steps"):.1f} · {M8(K,v,"t_step"):.4f} '
      f'| {M("r1",K,v,"sc"):.3f} · {M("r1",K,v,"steps"):.1f} · {M("r1",K,v,"t_step"):.4f} '
      f'| **{M("r8",K,v,"sc"):.3f} · {M("r8",K,v,"steps"):.1f} · {M("r8",K,v,"t_step"):.4f}** |')
w()
w('### 2.1 H16 / r1 — reject')
w()
ds1 = [M8(K, v, 'steps') - M('r1', K, v, 'steps') for K, v in PAIRS]
w(f'Lengthening the horizon while still replanning every step does improve the trajectory: **{min(ds1):.1f}–{max(ds1):.1f} fewer steps** in all six rows, and S&C reaches 1.000 everywhere (though the H8 reference is inside that interval at n=6, so the S&C move is not measurable).')
w()
_gr = [M("r1", K, v, "t_step") / M("r8", K, v, "t_step") for K, v in PAIRS]
_ds8 = [M("r8", K, v, "steps") - M("r1", K, v, "steps") for K, v in PAIRS]
w(f'It is rejected on cost. H16/r1 pays {min(rd):.1f}–{max(rd):.1f}× more per env step than H8/r1, and — because it still replans every step — that is also its per-tick cost.')
w()
w(f'Going to r8 costs back part of the step gain ({min(_ds8):+.1f} to {max(_ds8):+.1f} steps against H16/r1, worse in 4 of 6 rows)'.replace('(-', '(\u2212') + f' but buys {min(_gr):.1f}–{max(_gr):.1f}× lower amortised cost. Against H8/r1, H16/r8 still comes out ahead on steps in 4 of 6 rows (§2.2). That leaves H16/r1 with no regime where it is the right choice: strict per-tick budgets prefer H8/r1, buffered deployments prefer H16/r8.')
w()
w('### 2.2 H16 / r8 (H8+8) — adopt if buffering is available')
w()
w('**Steps, against H8/r1:**')
w()
w('| K | arm | H8 / r1 | H16 / r8 | Δ |')
w('|---|---|---|---|---|')
nb = nt = nw = 0
for K, v in PAIRS:
    a, b = M8(K, v, 'steps'), M('r8', K, v, 'steps'); d = b - a
    if abs(d) < 1.0: tag, nt = 'tie', nt + 1
    elif d < 0: tag, nb = f'**{d:+.1f}**'.replace('-', '−'), nb + 1
    else: tag, nw = f'{d:+.1f}', nw + 1
    w(f'| {K} | {NAME[v]} | {a:.1f} | {b:.1f} | {tag} |')
w()
imp = [M8(K, v, 'steps') - M('r8', K, v, 'steps') for K, v in PAIRS]
imp = [x for x in imp if x > 1.0]
worst = max(M('r8', K, v, 'steps') - M8(K, v, 'steps') for K, v in PAIRS)
w(f'{nb} better (by {min(imp):.1f}–{max(imp):.1f} steps), {nt} tie, {nw} worse by {worst:+.1f}. **Better.**')
w()
w('**Success-and-constraints, against H8/r1:**')
w()
w('| K | arm | H8 / r1 (n=60) | H16 / r8 (n=6) |')
w('|---|---|---|---|')
for K, v in PAIRS:
    b = M('r8', K, v, 'sc')
    w(f'| {K} | {NAME[v]} | {M8(K,v,"sc"):.3f} | {"**"+format(b,".3f")+"**" if b < 0.999 else format(b,".3f")} |')
w()
lo6, hi6 = clopper(6, 6); lo5, hi5 = clopper(5, 6)
w(f'Five rows up, one down. 6/6 has a 95% Clopper–Pearson interval of [{lo6:.3f}, {hi6:.3f}] and 5/6 of [{lo5:.3f}, {hi5:.3f}] — both overlap every H8 value in the column. **Not resolvable at n=6, in either direction.**')
w()
w('**Cost — two metrics with opposite signs:**')
w()
w('| K | arm | H8/r1 s/step | H16/r8 s/step | amortised | H8/r1 s/plan | H16/r8 s/plan | worst tick |')
w('|---|---|---|---|---|---|---|---|')
for K, v in PAIRS:
    a, b = M8(K, v, 't_step'), M('r8', K, v, 't_step')
    w(f'| {K} | {NAME[v]} | {a:.4f} | **{b:.4f}** | {a/b:.2f}× better | {a:.4f} | {b*8:.4f} | **{b*8/a:.1f}× worse** |')
w()
w('Under H8/r1 the policy runs on every env step, so its amortised cost *is* its per-plan cost. Under H16/r8 only one step in eight pays, so per-plan cost is 8× the amortised figure. Both columns come from the same run.')
w()
w(f'- **Buffered deployment** (pre-compute an 8-step segment): H16/r8 wins by {min(am):.1f}–{max(am):.1f}× on total compute.')
w(f'- **Per-tick deadline**: H8/r1 wins; H16/r8 is a regression of {min(lat):.1f}–{max(lat):.1f}×, worst case {M("r8",5,DV,"t_step")*8:.2f} s per tick for DPCC at K=5.')
w()
w('HardFlow\'s H16/8+8 assumes buffering — that is what "execute 8" means. Adopting the structure inherits the assumption; it is not stated anywhere in this project (§8.6).')
w()
hfr = [(M('r8', K, HV, 't_step') * 8) / M8(K, HV, 't_step') for K in (1, 2, 5)]
dpr = [(M('r8', K, DV, 't_step') * 8) / M8(K, DV, 't_step') for K in (1, 2, 5)]
w(f'The latency penalty is a flat {min(hfr):.1f}× for HardFlow at every K but grows to {max(dpr):.1f}× for DPCC, because DPCC\'s per-plan cost blew up with the horizon and HardFlow\'s barely moved (§1.3). Each of those ratios compares an arm to itself, so the candidate-count asymmetry cancels.')
w()
w('### 2.3 Decision table')
w()
w('| axis | H16/r1 vs H8/r1 | H16/r8 vs H8/r1 |')
w('|---|---|---|')
w(f'| steps | **better** (6 of 6 rows, {min(ds1):.1f}–{max(ds1):.1f}) | **better** ({nb} of 6 rows, {min(imp):.1f}–{max(imp):.1f}) |')
w('| S&C | unresolved at n=6 | unresolved at n=6 |')
w(f'| cost, amortised | **worse** {min(rd):.1f}–{max(rd):.1f}× | **better** {min(am):.1f}–{max(am):.1f}× |')
w(f'| cost, per tick | **worse** {min(rd):.1f}–{max(rd):.1f}× | **worse** {min(lat):.1f}–{max(lat):.1f}× |')
w('| **verdict** | **reject** | **adopt with buffering** |')
w()
w('---')
w()
PARTS.append('\n'.join(O)); O.clear()

# ───────────────────────── 3-5 ─────────────────────────
w('## 3. Did replan-8 actually run?')
w()
w('If the cache-and-replay path is correct, per-plan solver work must be identical to r1 and only the plan count changes.')
w()
w('| K | cadence | NFE / plan | NLP / plan | plans / episode | IPOPT fails / episode |')
w('|---|---|---|---|---|---|')
for K in (1, 2, 5):
    for cad in ('r1', 'r8'):
        b = (lambda x: f'**{x}**') if cad == 'r8' else (lambda x: x)
        w(f'| {K} | {b(cad)} | {b(f"{per_plan(cad,K,HV,"nfe"):.2f}")} | {b(f"{per_plan(cad,K,HV,"nlp"):.2f}")} '
          f'| {b(f"{plans_per_ep(cad,K,HV):.1f}")} | {fails_per_ep(cad,K,HV):.2f} |')
w()
w(f'(`{HV}`. plans/episode = mean over scenes of `ceil(steps / cadence)`; per-plan counters divide logged totals by `2 ×` that, because `n_trials=2`.)')
w()
w('NFE/plan matches HardFlow accounting exactly — `K + n_active` = ' + ', '.join(str(K + NA[K]) for K in (1, 2, 5))
  + ' — and NLP/plan = `n_active` = ' + ', '.join(str(NA[K]) for K in (1, 2, 5)) + ', for K = 1, 2, 5 at A=0.5. **Unchanged by cadence, as required.** '
  + f'The K=2 r8 reading of {per_plan("r8",2,HV,"nfe"):.2f} is the `ceil` estimate being off for episodes whose length is not a multiple of 8.')
w()
w(f'Plans per episode drop {plans_per_ep("r1",1,HV):.1f} → {plans_per_ep("r8",1,HV):.1f} at K=1, a {plans_per_ep("r1",1,HV)/plans_per_ep("r8",1,HV):.1f}× reduction (not exactly 8× because episodes end mid-plan).')
w()
w('**Wall clock:** full 3-K sweep in 26 min (K1 5m56s, K2 6m04s, K5 14m18s) against ~93 min for the r1 sweep (10m22s, 11m48s, 70m43s) — 3.5× faster end to end. Less than 8× because env stepping and model setup are cadence-independent.')
w()
w('**Provenance** (`run_provenance.json`, first live run of the U10.1 writer): `env_set` records `MF_HORIZON=16`, `MF_REPLAN_STEPS=8`, `HFFM_BATCH=1`, `HFFM_ACT_THRESHOLD=0.5`, `FMPCC_DPCC_THRESHOLD=0.5`; `resolved` records `horizon=16`, `replan_steps=8`, `checkpoint_horizon=16`, `hf_batch_size=1`, `batch_size_dpcc_arms=4`, `n_trials=2`, `seed=6`; yaml `sha256:5c1dccdf…`; git `5bc5db48…`, `dirty: true`. `checkpoint_horizon=16` matching `horizon=16` is the G1 guard passing — an H16-trained checkpoint, not an H8 one reinterpreted by a length-agnostic UNet. **`dirty: true` means commit `5bc5db4` does not fully describe the code that produced these numbers.**')
w()
w('---')
w()
w('## 4. Tightening is mandatory at r8')
w()
w('**Tightened arms hold.** Per-cell S&C (6 episodes), r1 → r8:')
w()
TC = ['dpcc-r-tightened', 'dpcc-c-tightened', 'dpcc-t-tightened',
      'hardflow_new-r-tightened', 'hardflow_new-c-tightened', 'hardflow_new-t-tightened']
w('| K | `dpcc-r-t` | `dpcc-c-t` | `dpcc-t-t` | `hf-r-t` | `hf-c-t` | `hf-t-t` |')
w('|---|---|---|---|---|---|---|')
for K in (1, 2, 5):
    w(f'| {K} | ' + ' | '.join(f'{M("r1",K,v,"sc"):.3f}→{M("r8",K,v,"sc"):.3f}' for v in TC) + ' |')
w()
w(f'Every 0.833 is one episode of six in one scene, and two of them move upward (`dpcc-t-t` at K=2 and K=5). At n=6, 6/6 spans [{lo6:.3f}, {hi6:.3f}] and 5/6 spans [{lo5:.3f}, {hi5:.3f}]. The claim this supports is that r8 does not visibly break S&C — not that it preserves it.')
w()
allc = [v for v in TC if all(M(c, K, v, 'sc') > 0.999 for c in ('r1', 'r8') for K in (1, 2, 5))]
w(f'`{allc[0]}` is the only arm at 6/6 in every cell of both cadences.')
w()
w('**Untightened arms collapse.**')
w()
w('| K | arm | violations / episode, r1 → r8 | S&C, r1 → r8 |')
w('|---|---|---|---|')
for K in (1, 2, 5):
    w(f'| {K} | `hardflow_new-{{r,c,t}}` | {M("r1",K,"hardflow_new-c","nviol"):.2f} → **{M("r8",K,"hardflow_new-c","nviol"):.2f}** '
      f'| {M("r1",K,"hardflow_new-c","sc"):.3f} → {M("r8",K,"hardflow_new-c","sc"):.3f} |')
w()
per = ', '.join(f'`{s.replace("-hard","")} {IDX[("r1",2,"hardflow_new-c",s)]["nviol"]:.0f}→{IDX[("r8",2,"hardflow_new-c",s)]["nviol"]:.0f}`' for s in SCENES)
mx = max(M('r8', K, 'hardflow_new-c', 'nviol') / max(M('r1', K, 'hardflow_new-c', 'nviol'), 1e-9) for K in (1, 2, 5))
w(f'Per scene at K=2: {per}. Increases of up to {mx:.0f}× are far outside n=6 noise.')
w()
w('**Mechanism.** Projection guarantees the constraint on the plan, at plan time. Under r1 the guarantee is refreshed every step and tracking error never accumulates. Under r8 the robot executes 8 steps open-loop and drifts; an untightened plan sits exactly on the constraint boundary, so any drift crosses it. Tightening supplies the margin that absorbs the drift.')
w()
w('`Tracking error` of the unguided `diffuser` arm (the only arm that logs it), per scene:')
w()
w('| K | r1 | r8 |')
w('|---|---|---|')
for K in (1, 2, 5):
    fa = '/'.join(f'{x:.3f}' for x in sorted(set(TRACK[(K, 'r1')])))
    fb = '/'.join(f'{x:.3f}' for x in sorted(set(TRACK[(K, 'r8')])))
    w(f'| {K} | {fa} | **{fb}** |')
w()
gt = max(TRACK[(5, 'r8')]) / TRACK[(5, 'r1')][0]
w(f'Drift grows with cadence, up to {gt:.1f}× at K=5.')
w()
w(f'> **Transferable result:** replan cadence and constraint tightening are coupled knobs. Executing 8 steps open-loop raises tracking error up to {gt:.1f}× and untightened violations up to {mx:.0f}×, while tightened projection is unaffected. HardFlow\'s H16/8+8 is affordable *because* the projection carries a margin.')
w()
w('---')
w()
PARTS.append('\n'.join(O)); O.clear()

# ───────────────────────── 5-7 + appendix ─────────────────────────
w('## 5. What these numbers cannot support')
w()
q = [M('r8', K, v, 't_step') for K in (1, 2) for v in (DV, HV)]
w(f'1. **n=6 cannot resolve S&C.** Every H16 S&C figure is 6 episodes, one seed. 6/6 and 0.867 are the same measurement at that n. Cost figures are near-deterministic and do not share this problem.')
w('2. **Amortised cost is not real-time cost.** Whether H8+8\'s gain is real depends on the buffering assumption (§2.2), which is a design decision this project has not made.')
w(f'3. **`avg_time` prints to 3 decimals.** At r8 / K=1–2 the values are {min(q):.4f}–{max(q):.4f}, so quantisation is ±{0.0005/max(q)*100:.0f}–{0.0005/min(q)*100:.0f}%. Only the K=5 r8 figures are precise; §1.2 uses r1 for this reason.')
w('4. **Candidate counts differ (4 vs 1).** Corrected for on the cost axis in §1.2. **Not** corrected on the quality axis: DPCC\'s S&C and steps edge at H8 may be bought by the 4-candidate fan, and nothing measured here separates that.')
w('5. **`replan_steps=8` was never swept.** 8 was chosen to match HardFlow. Where the untightened collapse begins is unmeasured.')
w('6. **No H16 diffusion baseline.** The DPCC-diffusion reference is H8 only.')
w('7. **One seed (6), one task (avoiding-d3il), one backbone (UNet).** Nothing here transfers to aligning, UAV, or the SiT/DiT backbones without a run.')
w()
w('---')
w()
w('## 6. Citable claims')
w()
g = [M('r1', K, v, 't_step') / M('r8', K, v, 't_step') for K, v in PAIRS]
w('**Defensible:**')
w()
w(f'> On avoiding-d3il, adopting HardFlow\'s planning structure (H=16, execute 8) reduces amortised planning cost by {min(g):.1f}–{max(g):.1f}× against per-step replanning at the same horizon, and by up to {max(am):.1f}× against the H8 per-step configuration, with no measurable loss in success-and-constraints for constraint-tightened projection. Per-plan solver cost is unchanged; the gain is a reduction in planning frequency, paid for with a {min(lat):.1f}–{max(lat):.1f}× increase in worst-case per-tick latency.')
w()
w(f'> Per constrained solve, doubling the planning horizon from 8 to 16 costs SLSQP ~{sum(sr)/3:.0f}× and IPOPT ~{sum(ir)/3:.2f}×, consistently at K = 1, 2 and 5. HardFlow\'s in-loop IPOPT scales near-linearly in the decision-variable count; the DPCC projector\'s post-hoc dense SLSQP scales superlinearly. Under a hard latency budget, HardFlow is the arm that survives growing H.')
w()
w(f'> Replan cadence and constraint tightening are coupled. Executing 8 steps open-loop raises trajectory tracking error up to {gt:.1f}× and untightened violations up to {mx:.0f}×, while tightened projection absorbs the drift and is unaffected.')
w()
w('**Not defensible:**')
w()
w('- That H16/r8 dominates H8/r1. It trades worst-case latency for throughput, and S&C is unresolved at n=6.')
w('- That r8 improves S&C.')
w(f'- That HardFlow beats the DPCC projector by {dp5/hf5:.0f}× on cost. That figure is ~4× candidate fan and ~{(dp5/hf5)/4:.1f}× solver; matched, it is {min(d1_5/hf5, dp5/h4_5):.1f}–{max(d1_5/hf5, dp5/h4_5):.1f}×, at H16 / K=5 only. At H16 K=1/2 and at every H8 cell, the matched-batch DPCC projector is cheaper.')
w()
w('---')
w()
w('## 7. H8+8 + HardFlow as the sim2real candidate — conditional')
w()
w('**Premise:** HardFlow never justified H=16 / execute-8. The paper states it once, in an appendix sentence, with no ablation and no comparison to the DPCC setup it says it follows; the value arrives with the flow-guidance codebase it forked. Full forensics: `../H8+8_U10/RESEARCH_did_HardFlow_justify_H16_T8.md`. **If we adopt the structure, the justification has to be ours.** The chain below is that justification, and it either closes or it does not.')
w()
w('### Condition A — is H8+8 HardFlow\'s own best configuration?')
w()
w('`hardflow_new-c-tightened`, same arm throughout, so the candidate-count asymmetry is irrelevant here. `S&C · steps · s per env step`:')
w()
w('| K | H8 / r1 | H16 / r1 | H16 / r8 | holds? |')
w('|---|---|---|---|---|')
for K in (1, 2, 5):
    a = (M8(K, HV, 'sc'), M8(K, HV, 'steps'), M8(K, HV, 't_step'))
    b = (M('r1', K, HV, 'sc'), M('r1', K, HV, 'steps'), M('r1', K, HV, 't_step'))
    c = (M('r8', K, HV, 'sc'), M('r8', K, HV, 'steps'), M('r8', K, HV, 't_step'))
    if c[0] < max(a[0], b[0]) - 0.02:
        v = f'**no** — S&C drops to {c[0]:.3f}'
    elif c[1] <= min(a[1], b[1]) + 0.5 and c[2] <= min(a[2], b[2]):
        v = '**yes** — dominant on all three'
    else:
        v = f'partly — cheapest, but {c[1]-min(a[1],b[1]):+.1f} steps vs H16/r1'
    w(f'| {K} | {a[0]:.3f} · {a[1]:.1f} · {a[2]:.4f} | {b[0]:.3f} · {b[1]:.1f} · {b[2]:.4f} '
      f'| **{c[0]:.3f} · {c[1]:.1f} · {c[2]:.4f}** | {v} |')
w()
w('**Holds at K=5 only.**')
w()
w('### Condition B — does H8+8 HardFlow beat the DPCC projector at every configuration?')
w()
w('At K=5, best `-tightened` DPCC arm of each configuration against `hardflow_new-*-t` at H16/r8:')
w()
w('| DPCC configuration | DPCC | HardFlow H16/r8 | holds? |')
w('|---|---|---|---|')
hf5 = (M('r8', 5, HV, 'sc'), M('r8', 5, HV, 'steps'), M('r8', 5, HV, 't_step'))
for lbl, g_ in (('H8 / r1', G8), ('H16 / r1', G16r1), ('H16 / r8', G16r8)):
    d = best_tight(g_, 'dpcc', 5)
    ok = (hf5[0] >= d[1] - 0.02) and hf5[1] < d[2] and hf5[2] < d[3]
    w(f'| {lbl} | `{d[0].replace("-tightened","-t")}` {d[1]:.3f} · {d[2]:.1f} · {d[3]:.4f} '
      f'| {hf5[0]:.3f} · {hf5[1]:.1f} · {hf5[2]:.4f} | {"**yes**" if ok else "no"} |')
w()
_, _, d1_5b, h4_5b = bm('H16', 5)
w(f'**Holds at K=5, and survives the batch correction:** matched at a common candidate count, HardFlow at H16/K=5 is still {min(d1_5b/D[("H16",5)][4], D[("H16",5)][3]/h4_5b):.1f}–{max(d1_5b/D[("H16",5)][4], D[("H16",5)][3]/h4_5b):.1f}× cheaper than the DPCC projector (§1.2). At K=1 and K=2 it does not hold in either direction — see the Q1 table.')
w()
w('### The chain closes on exactly one cell')
w()
w(f'**H16 / replan-8 / K=5 / `hardflow_new-*-tightened`** — S&C {hf5[0]:.3f} (6/6), {hf5[1]:.1f} steps, {hf5[2]:.4f} s per env step, {hf5[2]*8:.4f} s per plan. It is HardFlow\'s best configuration, it beats the DPCC projector at every configuration tested, and the cost advantage is not a batch artifact. **At K=1 and K=2 the chain breaks and the DPCC projector remains the better arm.**')
w()
w('### Why this cell is the sim2real candidate')
w()
w(f'1. **The constraint guarantee is per-sample, not per-cadence.** HardFlow\'s terminal safety property holds at the sampled trajectory (`h(x̂_N) ≤ 0`, exact at `t_N`); `T` appears in zero equations of the paper and is an environment-loop wrapper outside the algorithm (`RESEARCH_did_HardFlow_justify_H16_T8.md` §6.2). Nothing in the guarantee degrades at T=8 in principle.')
w(f'2. **Cheapest real-time budget in the grid.** {hf5[2]:.4f} s amortised, {hf5[2]*8:.4f} s worst tick — against the DPCC projector at the same configuration: {M("r8",5,"dpcc-c-tightened","t_step")*8:.2f} s (cheapest arm) to {M("r8",5,"dpcc-t-tightened","t_step")*8:.2f} s (best arm) per tick.')
sr_ = [D[('H16', K)][1] / D[('H8', K)][1] for K in (1, 2, 5)]
ir_ = [D[('H16', K)][2] / D[('H8', K)][2] for K in (1, 2, 5)]
w(f'3. **It scales the right way with horizon.** Real deployments want longer lookahead; per solve, doubling H costs IPOPT ~{sum(ir_)/3:.2f}× against SLSQP\'s ~{sum(sr_)/3:.0f}× (§1.3). The gap widens in HardFlow\'s favour as H grows.')
w('4. **B=1 means no candidate fan.** One deterministic trajectory, projected — no stochastic candidate selection to certify or reproduce.')
w(f'5. **Fewest steps in the grid** ({hf5[1]:.1f}), i.e. shortest executed trajectories.')
w()
w('### The risk that decides it, and it is a sim2real risk specifically')
w()
gt_ = max(TRACK[(5, 'r8')]) / TRACK[(5, 'r1')][0]
mx_ = max(M('r8', K, 'hardflow_new-c', 'nviol') / max(M('r1', K, 'hardflow_new-c', 'nviol'), 1e-9) for K in (1, 2, 5))
w(f'**T=8 executes 8 steps open-loop under a least-squares-fitted linear dynamics model.** Model error compounds across the executed prefix — and sim2real *is* model error. §4 already measures this in simulation, where the model is nearly exact: tracking error rises up to {gt_:.1f}× and untightened violations up to {mx_:.0f}×. On hardware the mismatch is larger, so the drift is larger.')
w()
w('Three consequences:')
w()
w('- **Tightening is not optional.** Every untightened arm collapses at r8 (§4). Any sim2real deployment of this cell must carry a margin, and the margin has to be sized against the *real* mismatch, not the simulated one.')
w('- **The margin and the cadence must be co-tuned.** They are coupled knobs (§4). A cadence sweep with tightening as the second axis (§8.3) is the minimum evidence needed before hardware.')
w(f'- **Buffering must actually be available.** {hf5[2]*8:.4f} s per plan, then 8 env steps played from the buffer. If the platform cannot buffer, this cell is not deployable and H8/r1 is the fallback (§2.3).')
w()
w('### Status')
w()
w('**Candidate, not a conclusion.** The chain closes on n=6, one seed, one task, in simulation, at one K. What it justifies today is a targeted evidence programme, not a hardware commitment:')
w()
w('| gate | what it settles | run |')
w('|---|---|---|')
w('| n=6 → n=300 at K=5, H16/r8 | whether the S&C 1.000 and the step lead are real | §8.1 |')
w('| `HFFM_BATCH=4` at H16/K=5 | whether the cost win is a batch artifact | §8.2 |')
w('| cadence × tightening sweep | how much margin T=8 needs, and whether T=8 is the right T | §8.3 |')
w('| dynamics-mismatch injection at r8 | the sim2real risk above, measured before hardware | **new — not yet planned** |')
w()
w('Until the last row exists, "H8+8 + HardFlow is our sim2real solution" is a hypothesis with one supporting cell.')
w()
w('---')
w()
w('## 8. Next runs')
w()
w('1. **5 seeds × `n_trials=20` at H16/r8, K ∈ {1,5}.** Every quality claim here is n=6-limited. Highest value, and cheap now that r8 runs 3.5× faster.')
u5, s5, i5, dp5b, hf5b = D[('H16', 5)]; h_b4 = (5 + NA[5]) * u5 + NA[5] * 4 * i5
w(f'2. **`HFFM_BATCH=4` at H16, K=5, on the `-r`/`-t` arms only** (`-c` collapses at B>1, §1.4). Decides whether the one surviving HardFlow cost win is real. Predicted: HardFlow at B=4 lands near **{h_b4:.2f} s/step** against DPCC\'s {dp5b:.2f}, i.e. {dp5b/h_b4:.1f}× cheaper. Run at r1, where `avg_time` is not quantisation-limited. The H8 half of this control already exists (C109/C117, §1.4); only the H16 point is missing.')
w('3. **Cadence sweep `MF_REPLAN_STEPS ∈ {2,4,8,16}`** at K=5, tightened and untightened. Locates where the untightened collapse starts and whether 8 is the right operating point.')
w('4. **Horizon sweep H ∈ {8,12,16,24} at K=5, batch matched.** §1.3 predicts per-solve parity at H ≈ 10 from two points; a third point tests it.')
w('5. **Per-solve latency histogram** instead of the amortised mean, so §2.2\'s per-tick column is measured rather than reconstructed by multiplying by 8.')
w('6. **Write down the buffering assumption** (§2.2). A decision, not a run. Until it is stated, every cost claim in the paper is ambiguous.')
w('7. **Dynamics-mismatch injection at r8** — perturb the fitted linear model and measure how fast the tightened arms degrade across the 8 open-loop steps. The gate §7 identifies as missing.')
w('8. *Not yet:* H16 diffusion baseline retrain. Worth it only once (1) shows H16/r8 holding at scale.')
w()
w('---')
w()
w('## Appendix — all 13 variants × 3 K, mean over 3 scenes, n=6 per cell')
w()
w('`S&C · steps · violations per episode · s per env step`')
w()
for K in (1, 2, 5):
    w(f'### K = {K}')
    w()
    w('| variant | r1 | r8 |')
    w('|---|---|---|')
    for v in VARS:
        a = [M('r1', K, v, k) for k in ('sc', 'steps', 'nviol', 't_step')]
        b = [M('r8', K, v, k) for k in ('sc', 'steps', 'nviol', 't_step')]
        w(f'| `{v}` | {a[0]:.3f} · {a[1]:.1f} · {a[2]:.2f} · {a[3]:.4f} | {b[0]:.3f} · {b[1]:.1f} · {b[2]:.2f} · {b[3]:.4f} |')
    w()
w('---')
w()
w('*Generated by `python3 gen_DA_20260818.py` in this folder, from `gen_DA_20260818_rows.json` (234 parsed `eval_*.log` files, job 24650) and the H8 `candidates_multidimensional_aggregated.csv`.*')
PARTS.append('\n'.join(O))
print('\n'.join(PARTS))
